### ISSUE TITLE
Support icons from Compiz

### ISSUE THREAD

**Issue by PanderMusubi** [PanderMusubi/inkscape-open-symbols#107]
Please, support icons from Compiz

The SVG files can be found at

https://git.launchpad.net/compiz/tree/compizconfig/ccsm/images/scalable

and the license is

https://git.launchpad.net/compiz/tree/COPYING

Offer these as `Compiz Icons [Apps Set]` and `Compiz Icons [Categories Set]`

**Comment by denilsonsa** [comment]
Those icons seem very specific for Compiz itself (icons for each of its plugins). I'm not sure they are relevant to be included in this repository, in my humble opinion.

**Comment by PanderMusubi** [comment]
Agreed. Also there isn't much development on them so would be too much work of limited collection that is not going to be used much in this context.
