### ISSUE TITLE
Regarding Arch linux build

### ISSUE THREAD

**Issue by jmarca** [PanderMusubi/inkscape-open-symbols#109]
Hi just noticed over at Arch linux (https://aur.archlinux.org/packages/inkscape-open-symbols-git/) that you opened an issue.  The maintainer (I think it is github user @vinipsmaker ; apologies to @vinipsmaker if not!)  said "If the build script is outdated, then we have a case. Could you explain the problem?"  

I looked at the build script and it is INDEED out of date.

The build (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=inkscape-open-symbols-git) says:

```
  for i in \
      font-awesome \
          genericons \
          gnome-icon-theme \
          humble-ui \
          material-design \
          octicons \
          suru-icons \
      ; do
    find "$i" -mindepth 1 -iname '*.svg' \
         -exec 'cp' '{}' "${pkgdir}/usr/share/inkscape/symbols" ';'
  done
```

Obviously, the issue is that they've hardcoded the symbol directories, and you've added some in the interim (and changed gnome, I guess).  By my accounting, the list should now be:

```
CircuiTikZ
dashicons
emoji-one
entypo
font-awesome
genericons
gnome
humble-ui
iconic
ionicons
material-design
octicons
sjjb
stateFace
suru-icons
taiga
weathericons
```

I don't use Arch and don't feel like creating an account there to post a fix, so I'm posting here and hopefully you will find this useful.

Also, as this *might* help...in my Dockerfile for inkscape (which is why I was poking around the Arch repo), I'm just using the find command directly, but with -mindepth set to 2, as follows:

```
RUN mkdir /symbols \
        && git clone --depth 1 https://github.com/Xaviju/inkscape-open-symbols /usr/src/ \
        && find /usr/src -mindepth 2 -type f -name "*.svg"   -exec 'cp' '{}' "/symbols" ';'
```

This gets around having to specify the icon directories.  The mindepth 2 is required to make sure the script doesn't pick up your template.svg in the root directory.

Of course, the Arch people may *want* to specify the actual directories in order to have more control, make sure licenses are conforming, etc.

Hope that helps.

**Comment by Xaviju** [comment]
Hey @jmarca seems that the package has been taken by another maintainer and it says that the package has been updated recently.
Would that fix this issue?

**Comment by jmarca** [comment]
I’ll check. I don’t use arch, but perhaps I can dummy something up using Docker.

**Comment by denilsonsa** [comment]
This seems fixed in https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=inkscape-open-symbols-git&id=c8f309a8cfeefa441140f6f3ee3beb1dbeb83083

I think this issue is now obsolete and can be closed.

**Comment by PanderMusubi** [comment]
Closing, please reopen if needed.
