### ISSUE TITLE
Transfering ownership of this repo

### ISSUE THREAD

**Issue by Xaviju** [PanderMusubi/inkscape-open-symbols#122]
Since I am no longer a inkscape user and cannot maintain this large SVG codebase I'm looking to transfer the ownership of this repo to someone who is interested in keeping it up to date.
Please if you are interested explain below would you be interested in maintaining the repo or ask anything.

**Comment by PanderMusubi** [comment]
You can also make a post at https://opensourcedesign.net/jobs/

**Comment by pathumego** [comment]
Would Inkscape project be interested in hosting this in their Gitlab setup? But that would mean the  Github-only-community would be missing out.

**Comment by PanderMusubi** [comment]
It is not so much the hosting I think. Both is git. First find a maintainer, if they want to move it later, fine.

**Comment by Xaviju** [comment]
> You can also make a post at https://opensourcedesign.net/jobs/

Done

**Comment by Moini** [comment]
Posted to Inkscape's developer chat channel.

**Comment by PanderMusubi** [comment]
I _might_ be interested in taking over this repo after June, but also need help getting to know all the scripts, pitfalls, etc.

**Comment by Moini** [comment]
@PanderMusubi Inkscape offers hosting and help, making this an official part of the Inkscape project, at https://gitlab.com/inkscape/extras , if someone would take on maintainership.

@doctormo would be the one to contact about this, if you'd like to join us officially in the summer.

**Comment by Xaviju** [comment]
Great news!!

@PanderMusubi I can explain the code to you if you want to take over the repo, but actually most of the scrips are outdated and can be deleted. I have been doing it manually and using icomoon for most of the SVG generation work because it does it better and has a decent UI.

@Moini This is awesome! Thanks.

**Comment by Xaviju** [comment]
Hi everyone,

With the upcoming release of [Penpot](https://penpot.app/) I am deprecating this repo. This is a last call if anyone wants to take over this repo as a maintainer. 
Please read the full issue and, if you are interested, comment here, so we can talk about the transference process. 

Thanks everyone.

**Comment by PanderMusubi** [comment]
I would like to maintain it, but need to worked in, e.g. make a new release.

**Comment by Xaviju** [comment]
OK @PanderMusubi, I'll begin the transfer process. 
Please email me with anything you need to know about the repo. I'll stay around for a while to help you anyway. :)

Thanks

**Comment by Xaviju** [comment]
Oh sorry I keep this issue open in case @Moini and the Inkscape team has something to say about this: https://github.com/Xaviju/inkscape-open-symbols/issues/122#issuecomment-620687519

**Comment by doctormo** [comment]
Only that you should consider publishing the symbols on inkscape.org so the new extensions manager can install them as a symbols pack. Come to chat.inkscape.org if unsure.

**Comment by PanderMusubi** [comment]
Sounds like a good idea, I will discuss this there further.

**Comment by PanderMusubi** [comment]
@doctormo can you make a new issue regarding your suggestion for the extension manager? Thank I can close this one and we investigate that further in the new issue. Thanks.

**Comment by PanderMusubi** [comment]
See also https://github.com/PanderMusubi/inkscape-open-symbols/issues/136
