### ISSUE TITLE
Add inkscape-open-symbols to the Symbols gallery on the Inkscape website

### ISSUE THREAD

**Issue by Moini** [PanderMusubi/inkscape-open-symbols#124]
Hi @Xaviju !

Could you please add a link to your repository at https://inkscape.org/gallery/=inkscape-symbol-set/ ? It would be great if the set could be found more easily by users.

I could do it myself, but I'd prefer if the real owner did it. 

Not sure what to use for the license, though. We could add a new one, if needed.

**Comment by Xaviju** [comment]
Cannot upload just a link, it actually requires an SVG file (a symbol set). This repositiory has too many symbol sets to upload and maintain each of them. Is there an alternative to just link an external resource instead of uploading it?

**Comment by PanderMusubi** [comment]
See #136
