### ISSUE TITLE
two different svg files with the same name, one working, one broken

### ISSUE THREAD

**Issue by KirstenRK** [PanderMusubi/inkscape-open-symbols#131]
Hi PanderMusubi,
I have been testing symbolsets under Windows and MacOS.
When I download the complete zip file with all the svg's in it, and unzip it, I can install them without a problem.

But when I download for example this single file, weather-icons.svg by going to this link, right click on the svg file and **save link as...** it gives a svg file (162 kB big) that I cannot open at all:
https://github.com/PanderMusubi/inkscape-open-symbols/tree/master/weathericons

If I go to this link, click on the svg file and click on the image and choose **save image as**, it downloads a different svg file (41kB), which works correct.
https://github.com/PanderMusubi/inkscape-open-symbols/blob/master/weathericons/weather-symbols.svg

After installation of this single 'broken' file, the name is not correct in the list of symbol sets.
When I click on this specific set, under Windows, Inkscape crashes.
When I click on it under MacOS, it loads a different set.
The other sets take 60 seconds to load under MacOS.
Once I delete this specific file, everything works normal again.

**Comment by KirstenRK** [comment]
So, right now it is a conclusion that the bigger download is a html page, not a symbol's set?
We have been disccussing this bug with the symbol's sets under Inkscape here:
[https://gitlab.com/inkscape/inbox/-/issues/4653](url)

**Comment by KirstenRK** [comment]
On the first link that I give, there is no Raw button. There is a short link with the name weather-symbols.svg. If you right-click it and download it, it downloads a corrupt svg file with the same name as the set that you are looking for.
I say it is a design flaw in the website that makes a lot of people install the wrong file that give bugs in Inkscape.

**Comment by Moini** [comment]
@KirstenRK Yes, that's because you're looking at the directory, not at the file.

I'm suggesting to close this issue, it's not something that is related to the icon set, only to not being familiar with websites about version control.
