### ISSUE TITLE
improvements in readme.md

### ISSUE THREAD

**Issue by yashpalgoyal1304** [PanderMusubi/inkscape-open-symbols#133]
hi, i can clean the readme file and make a merge request. will that be accepted? is there a will to accept changes to those??

**Comment by yashpalgoyal1304** [comment]
this question might seem weird/shady, but no shade involved. i am just asking 'cz it takes time to cleanup, and it kinda hurts when the mr gets blantantly ignored in the end. so, better to work on it only if there's a will in upstream to accept :)

**Comment by PanderMusubi** [comment]
Yes, PRs are being accepted. Why does the README.md need to be cleared for an improvement? Merge requests are not supported here on GitHub, pull requests are.

**Comment by yashpalgoyal1304** [comment]
> Why does the README.md need to be cleared

no, i meant "clean up" as in to make the source of readme more readable and more maintainable. does that make sense?

**Comment by PanderMusubi** [comment]
Thanks
