### ISSUE TITLE
A Script To Separate The Symbols

### ISSUE THREAD

**Issue by cheznewa** [PanderMusubi/inkscape-open-symbols#139]
Hi/Hello is possible to add a script for separate all symbols, from single SVG symbols set (dedictated for inskscape) to individual SVGs separated?

for use other software, not only in inkscape.

Newa Our Master.

**Comment by PanderMusubi** [comment]
Most of the sets are created from individusl files upstream. Best is to look there, especially if you are going to use them as SVG for other things than Inkscape symbols.
