### ISSUE TITLE
Flag semaphore and maritime signal flags

### ISSUE THREAD

**Issue by Moini** [PanderMusubi/inkscape-open-symbols#149]
Hi all,

could someone please run these two sets of files through the gulp script and share the resulting two svg-sprite.svg files here, so I can continue editing them and creating a PR for them?

These are already optimized.

[flag-semaphore.zip](https://github.com/PanderMusubi/inkscape-open-symbols/files/13795984/flag-semaphore.zip)

[maritime-signal-flags.zip](https://github.com/PanderMusubi/inkscape-open-symbols/files/13795985/maritime-signal-flags.zip)

**Comment by PanderMusubi** [comment]
Yes, give it a couple of days.

**Comment by PanderMusubi** [comment]
Running them now.

**Comment by PanderMusubi** [comment]
I ran them with

    gulp --max-old-space-size=4096 --iconset maritime-signal-flags --dest maritime-signal-flags
    gulp --max-old-space-size=4096 --iconset flag-semaphore --dest flag-semaphore

the result is in:

[sprites.tar.gz](https://github.com/PanderMusubi/inkscape-open-symbols/files/14049285/sprites.tar.gz)

Looking forward to your PR.

**Comment by Moini** [comment]
Thank you, going to look at it today!

**Comment by Moini** [comment]
Mmh, okay, so that didn't work at all because it removes all color. So it needs to be done manually, unfortunately.

**Comment by Moini** [comment]
Finally done: https://github.com/PanderMusubi/inkscape-open-symbols/pull/151

**Comment by PanderMusubi** [comment]
Thanks, also tested it. For users of flatpak:

    cp nautic-alphabets/* ~/.var/app/org.inkscape.Inkscape/config/inkscape/symbols/
