### ISSUE TITLE
Similar project for sound notifications

### ISSUE THREAD

**Issue by PanderMusubi** [PanderMusubi/inkscape-open-symbols#33]
Are some people here interested to start a similar project for audacity (or another sound editing software) with sets of sound notifications?

**Comment by victorwestmann** [comment]
Do you already have the library with you or we would start everything from scratch?

**Comment by PanderMusubi** [comment]
I have a library in a DEB-package. Will add notifications from GNOME et cetera and put it up for refactoring and extending. Good way to start?

**Comment by victorwestmann** [comment]
Is it already vector based and needs some cleaning or would it need to be
vectorized?

**Comment by PanderMusubi** [comment]
Ah, it would be a library for audio files, which can be used in relation to icons. So mostly notification sounds. No vectorisation there. More OGG files and such.

**Comment by PanderMusubi** [comment]
Sorry to (ab)use this issue. Please see what packages are interesting to add by looking at:

`find /usr/share/ -name '*.ogg'|more`

`find /usr/share/ -name '*.ogg' -exec dpkg -S {} \;|more`

`find /usr/share/ -name '*.ogg' -exec dpkg -S {} \;|awk -F ': ' '{print $1}'|sort|uniq`

**Comment by PanderMusubi** [comment]
I will start with:
* indicator-power
* ubuntu-sounds
* gnome-control-center-data
* gnome-shell-pomodoro-data

**Comment by Xaviju** [comment]
Is this active or should I close it?

**Comment by victorwestmann** [comment]
I'm still trying to understand what is the purpose of this thread. Could you expand more on this topic?

**Comment by Xaviju** [comment]
I think @PanderMusubi is figuring out is there is people interested in create collections of audio files in a new repo.
> Ah, it would be a library for audio files, which can be used in relation to icons. So mostly notification sounds. No vectorisation there. More OGG files and such.

**Comment by PanderMusubi** [comment]
Yes, that's it.

**Comment by victorwestmann** [comment]
Hi @PanderMusubi I would like to join and be part of it. What is the project address? Where will these sounds be used at? Thanks.

**Comment by PanderMusubi** [comment]
There is no repo yet for it. Perhaps (if it is okay with Xaviju) discuss a bit more here. I think a meta package would cover it as most of these are already available as Debian/Ubuntu package. What I find at the moment is:
* sound only
  * ubuntu-sounds
* more than only sounds:
  * gnome-control-center-data

Please add more as research.

**Comment by Xaviju** [comment]
@PanderMusubi sure! Only remember to close this issue when the new repo has been created and please add a link here so we can follow the evolution. :)
