### ISSUE TITLE
Create a static website for Inkscape Open Symbols

### ISSUE THREAD

**Issue by Xaviju** [PanderMusubi/inkscape-open-symbols#57]
It would be nice to have a small static website displaying the list of symbols and how to use them. Something as the README but with better User Experience.

Any ideas on what would be nice to have?

Basics:
- A list of symbols sets
- A basic how to install them on different platforms
- A how to contribute and current contributors.
- Latest releases.

More?

**Comment by PanderMusubi** [comment]
A screencast of how to use them

Choose a representative symbol for each symbol set.

Does this project have/need an icon?

https://inkscape-open-symbols.github.io ?

What most people in the non-inkscape world (and largely in the inkscape world) don't know yet, is that this is an extremely powerful addition to a vector drawing program. Many designers of apps and web sites potentially could start using this. So at the same time, to continue this project, add possibility for donations via bitcoin, flattr, paypal and bountysource. The number of symbol sets is already large, so better throttle the addition of new ones and use donations to keep maintaining this project and making it as easy to install and use and see what license belongs to what symbol. Perhaps give a talk on it at for example FOSDEM 2018 in the open design devroom when this project has completely matured. Anyway, just my thoughts on this at this moment.

**Comment by Moini** [comment]
+1 for the icon (how would an icon for icons look like?...), and for the basics @Xaviju mentioned. The other suggestions from @PanderMusubi go beyond the basics, for me, although they're good ideas for later on (of course if someone happens to be at FOSDEM anyway, a short 5-min flash talk could be nice :)). 

(Playing with them, I just found another (fun + silly) use: In children's drawing apps, there are often stamps that make it easy to create a drawing. I made a field with carrots ;-) )

**Comment by PanderMusubi** [comment]
For sure I will mention it quickly in my talk on FOSDEM next month, but no flash presentations there are possible.

**Comment by Moini** [comment]
They call it 'lightning talks', but the program is full by now, of course :) (didn't know the dates)

**Comment by Moini** [comment]
You'll be talking about fonts, right?

**Comment by PanderMusubi** [comment]
Yeah. You going too?

**Comment by Moini** [comment]
Nope. We've been thinking about going, to present our software deployment thing, but standing in a booth twice a year is sufficient at the moment. So much else to do! (but I heard only good things about it)

**Comment by Xaviju** [comment]
Ok so summary of contents of the website for a first MVP we agreed:

- A list of symbols sets 
- A basic how to install them on different platforms
- A screencast of how to use them
- A how to contribute and current contributors.
- Latest releases.
- Choose a representative symbol for each symbol set.

About the last one, I'll go with a screenshot of the symbolset instead of a representative icon because not all symbolsets are meant to be icons. A symbolset, as in HumbleUI, could be a set of UI components. But I get the idea of having a representation of each one. Just my thought.

**Does this project have/need an icon?**
@PanderMusubi 
I was thinking of asking for help in the [Open Source Design](Does this project have/need an icon?) repo. Give them this information of what contents the page should have and work with them in creating an image for the project and maybe some wireframes/UI of the page. I'll be happy to work on the front-end code.

**(Playing with them, I just found another (fun + silly) use: In children's drawing apps, there are often stamps that make it easy to create a drawing. I made a field with carrots ;-) )**
@Moini 
That looks like an amazing amazing project. it would be nice to find an illustrator to create some templates with background illustrations and symbols attached to that item. Childs could start playing with Inkscape.

@PanderMusubi I'll be at FOSDEM next month!

**Comment by Moini** [comment]
This is the link for job proposals for the Open Source Design project:

http://opensourcedesign.net/opensrcdesignjobs/

Probably a three- or even just two-page static site would be sufficient, no? 
One for presentation, one or two for documentation (with optional space for video). Not sure if more than the current release needs to be listed, we could just link to the list here on gh (but I don't assume they'd be of much interest). 
The other iconset websites are kept very minimalistic, too, and that appears suitable to me. People just want to find out what's there, then download their set, and start working with it :)

I can help by providing list images of icons and texts. Design isn't my specialty :)

**Comment by Xaviju** [comment]
Done! The form they provide didn't work so I had to do a pull request so it took a bit longer.  https://github.com/opensourcedesign/jobs/pull/142

**Comment by Xaviju** [comment]
@Moini I won't focus only on iconsets, the project can also provide UI stencils, avatar sets, etc. although icons are the very first thing that comes to our minds because are very useful.

**Comment by Xaviju** [comment]
Please check the referenced issue for the work being done at Open Source Design if you want to add some feedback

**Comment by Moini** [comment]
I'll watch and learn, @Xaviju. I'm a total noob to the process (but I agree about the thunderbolt :) - in my very simple understanding, I didn't get the 'open' reference, and it just looked a bit off).

**Comment by Moini** [comment]
Just had an idea, not sure if it could be built upon:

![bildschirmfoto_2017-01-18_02-18-30](https://cloud.githubusercontent.com/assets/3240233/22046981/7f043af8-dd24-11e6-99b6-89c8c600b1d5.png)

(looking at it now, I think this somehow looks familiar... but can't say what it's similar to...)

**Comment by Erioldoesdesign** [comment]
Hi there! this issue is linked in an Open source design.net job: https://opensourcedesign.net/jobs/jobs/2017-01-14-inkscape-open-symbols-ux-ui

Can I close the job request?
(If I don't get a reply in 2 weeks from this date I'll close it :) )

**Comment by Xaviju** [comment]
Hi @Erioldoesdesign 
I opened the job a while ago, and I think it can be closed safely. Sorry I didn't do it before.
Thanks!
